import Head from 'next/head';
// import Link from 'next/link';
// import { CardList } from '../../layout/cardList/cardList';
// import { Main } from '../main/main';
// import Image from 'next/image';
import './home.module.scss';

const Home = () => {
  return (
    <>
      <Head>
        <title>ColdBeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
