import Head from 'next/head';
import './home.module.scss';

const Home = () => {
  return (
    <>
      <Head>
        <title>ColdBeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
